### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by andimik** [newspaperman/tsniv2ni#2]
Grüß dich,

could you tell me what I did wrong here? I have successfully compiled it in my previous PCs. But today I installed it on a fresh Kubuntu 18.04 and it failed:

> $ make
> g++ -o tsniv2ni tsniv2ni.cpp
> tsniv2ni.cpp:30:42: error: narrowing conversion of ‘255’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
>  const char fsync0[]={0xff, 0x07,0x3a,0xb6};
>                                           ^
> tsniv2ni.cpp:30:42: error: narrowing conversion of ‘182’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
> tsniv2ni.cpp:31:42: error: narrowing conversion of ‘255’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
>  const char fsync1[]={0xff, 0xf8,0xc5,0x49};
>                                           ^
> tsniv2ni.cpp:31:42: error: narrowing conversion of ‘248’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
> tsniv2ni.cpp:31:42: error: narrowing conversion of ‘197’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
> Makefile:6: recipe for target 'tsniv2ni' failed
> make: *** [tsniv2ni] Error 1
> 

here is the g++ version:

> $ g++ --version
> g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0
> Copyright (C) 2017 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by andimik** [comment]
I will try https://github.com/satdreamgr/tsniv2ni instead.

**Comment by andimik** [comment]
Closed this as https://github.com/satdreamgr/tsniv2ni works indeed ...

**Comment by newspaperman** [comment]
It's also merged into my tree now :)
